version: '3.8'

networks:
  app:

volumes:
  guest-account-data:

services:
  app:
    image: kristobalus/guest-keeper:1.0.1
    entrypoint: npm run start
    environment:
      DATA_PATH: "/data"
    volumes:
      - guest-account-data:/data
    ports:
      - "80:3000"
    networks:
      - app
